# -*- coding: utf-8 -*-
"""Competition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3KlH8IdhYEYCkYp-h4Zlfn67uDTSmoE
"""

!pip install catboost

import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import lightgbm as lgb
from catboost import CatBoostClassifier

warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────────────────────────────────────
# 1. LOAD DATA & INITIAL SETUP
# ─────────────────────────────────────────────────────────────────────────────
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

test_ids = test_df['Id']
y = train_df['Drafted'].values

train_features = train_df.drop(columns=['Id', 'Drafted'])
test_features = test_df.drop(columns=['Id'])

df = pd.concat([train_features, test_features], axis=0).reset_index(drop=True)

# ─────────────────────────────────────────────────────────────────────────────
# 2. FEATURE ENGINEERING (Strictly Reverted to 0.848 Golden Features)
# ─────────────────────────────────────────────────────────────────────────────
COMBINE_METRICS = ['Sprint_40yd', 'Vertical_Jump', 'Bench_Press_Reps',
                   'Broad_Jump', 'Agility_3cone', 'Shuttle']

# A. Base Categorical Handling
cat_features = ['Player_Type', 'Position_Type', 'Position', 'School']
for col in cat_features:
    df[col] = df[col].fillna('Unknown').astype(str)

# B. School Prestige
df['School_Count'] = df['School'].map(df['School'].value_counts())

# C. Missingness Flags
df['n_missing_combine'] = df[COMBINE_METRICS].isnull().sum(axis=1)
df['skipped_speed'] = df['Sprint_40yd'].isnull().astype(int)

# D. Advanced Athletic Composites
df['BMI'] = df['Weight'] / (df['Height'] ** 2)
df['Speed_Score'] = (df['Weight'] * 200) / (df['Sprint_40yd'] ** 4)
df['Burst_Score'] = df['Vertical_Jump'] + df['Broad_Jump']
df['Agility_Score'] = df['Agility_3cone'] + df['Shuttle']
df['Power_Ratio'] = df['Bench_Press_Reps'] / df['Weight']

# E. Positional Percentiles & Z-Scores
for col in COMBINE_METRICS + ['Height', 'Weight', 'BMI', 'Speed_Score']:
    df[f'{col}_pos_pct'] = df.groupby(['Position'])[col].rank(pct=True)
    pos_mean = df.groupby('Position')[col].transform('mean')
    pos_std = df.groupby('Position')[col].transform('std').replace(0, 1).fillna(1)
    df[f'{col}_pos_z'] = (df[col] - pos_mean) / pos_std

# ─────────────────────────────────────────────────────────────────────────────
# 3. PREPARE BASE DATASET
# ─────────────────────────────────────────────────────────────────────────────
# Ensure categoricals are properly typed for native tree splits
for col in cat_features:
    df[col] = df[col].astype('category')

X_train = df.iloc[:len(train_df)].copy()
X_test = df.iloc[len(train_df):].copy()

# ─────────────────────────────────────────────────────────────────────────────
# 4. OUT-OF-FOLD BASE MODELS (5-Seed Averaging on 0.848 Params)
# ─────────────────────────────────────────────────────────────────────────────
N_SPLITS = 10
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=2024)

# 5 Seeds to guarantee maximum test-set stability
SEEDS = [42, 100, 777, 888, 2024]

oof_cb = np.zeros(len(X_train))
oof_lgb = np.zeros(len(X_train))
test_cb = np.zeros(len(X_test))
test_lgb = np.zeros(len(X_test))

print(f"── Training CatBoost & LightGBM ({len(SEEDS)} Seeds per Fold) ──")

for fold, (trn_idx, val_idx) in enumerate(skf.split(X_train, y)):
    print(f"\n--- Fold {fold + 1}/{N_SPLITS} ---")

    X_tr, y_tr = X_train.iloc[trn_idx], y[trn_idx]
    X_va, y_va = X_train.iloc[val_idx], y[val_idx]

    cb_val_preds = np.zeros(len(X_va))
    cb_test_preds = np.zeros(len(X_test))
    lgb_val_preds = np.zeros(len(X_va))
    lgb_test_preds = np.zeros(len(X_test))

    for seed in SEEDS:
        # 1. CatBoost (Exact 0.848 parameters)
        cb = CatBoostClassifier(iterations=2000, learning_rate=0.02, depth=6,
                                cat_features=cat_features, random_seed=seed+fold, verbose=0)
        cb.fit(X_tr, y_tr, eval_set=(X_va, y_va), early_stopping_rounds=150)

        cb_val_preds += cb.predict_proba(X_va)[:, 1] / len(SEEDS)
        cb_test_preds += cb.predict_proba(X_test)[:, 1] / len(SEEDS)

        # 2. LightGBM (Exact 0.848 parameters)
        lgb_model = lgb.LGBMClassifier(n_estimators=2000, learning_rate=0.015, max_depth=6, num_leaves=31,
                                       subsample=0.8, colsample_bytree=0.7, random_state=seed+fold, verbose=-1)
        lgb_model.fit(X_tr, y_tr, eval_set=[(X_va, y_va)], callbacks=[lgb.early_stopping(150, verbose=False)])

        lgb_val_preds += lgb_model.predict_proba(X_va)[:, 1] / len(SEEDS)
        lgb_test_preds += lgb_model.predict_proba(X_test)[:, 1] / len(SEEDS)

    oof_cb[val_idx] = cb_val_preds
    oof_lgb[val_idx] = lgb_val_preds

    test_cb += cb_test_preds / N_SPLITS
    test_lgb += lgb_test_preds / N_SPLITS

    # Print Fold AUCs (Averaged across 5 seeds)
    print(f"  CatBoost Fold AUC: {roc_auc_score(y_va, oof_cb[val_idx]):.5f}")
    print(f"  LightGBM Fold AUC: {roc_auc_score(y_va, oof_lgb[val_idx]):.5f}")

# ─────────────────────────────────────────────────────────────────────────────
# 5. HARDCODED BLEND (Clean Probabilities)
# ─────────────────────────────────────────────────────────────────────────────
print("\n── Base Model Overall OOF AUCs ──")
print(f"CatBoost : {roc_auc_score(y, oof_cb):.5f}")
print(f"LightGBM : {roc_auc_score(y, oof_lgb):.5f}")

# Keeping your proven 85/15 split exactly as it was
final_oof = (oof_cb * 0.85) + (oof_lgb * 0.15)
final_test = (test_cb * 0.85) + (test_lgb * 0.15)

print(f"\n🏆 Final Stacked Ensemble OOF AUC: {roc_auc_score(y, final_oof):.5f} 🏆")

# ─────────────────────────────────────────────────────────────────────────────
# 6. SAVE SUBMISSION
# ─────────────────────────────────────────────────────────────────────────────
sub = pd.DataFrame({
    'Id': test_ids,
    'Drafted': final_test
})

sub.to_csv('submission_0848_purified.csv', index=False)
print("\nPredictions securely saved to submission_0848_purified.csv")

"""BEST ONE ABOVE"""

import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from scipy.stats import rankdata # Added for Rank Blending
import lightgbm as lgb
from catboost import CatBoostClassifier

warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────────────────────────────────────
# 1. LOAD DATA & INITIAL SETUP
# ─────────────────────────────────────────────────────────────────────────────
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

test_ids = test_df['Id']
y = train_df['Drafted'].values

train_features = train_df.drop(columns=['Id', 'Drafted'])
test_features = test_df.drop(columns=['Id'])

df = pd.concat([train_features, test_features], axis=0).reset_index(drop=True)

# ─────────────────────────────────────────────────────────────────────────────
# 2. FEATURE ENGINEERING (Strictly Reverted to 0.848 Golden Features)
# ─────────────────────────────────────────────────────────────────────────────
COMBINE_METRICS = ['Sprint_40yd', 'Vertical_Jump', 'Bench_Press_Reps',
                   'Broad_Jump', 'Agility_3cone', 'Shuttle']

# A. Base Categorical Handling
cat_features = ['Player_Type', 'Position_Type', 'Position', 'School']
for col in cat_features:
    df[col] = df[col].fillna('Unknown').astype(str)

# B. School Prestige
df['School_Count'] = df['School'].map(df['School'].value_counts())

# C. Missingness Flags
df['n_missing_combine'] = df[COMBINE_METRICS].isnull().sum(axis=1)
df['skipped_speed'] = df['Sprint_40yd'].isnull().astype(int)

# D. Advanced Athletic Composites
df['BMI'] = df['Weight'] / (df['Height'] ** 2)
df['Speed_Score'] = (df['Weight'] * 200) / (df['Sprint_40yd'] ** 4)
df['Burst_Score'] = df['Vertical_Jump'] + df['Broad_Jump']
df['Agility_Score'] = df['Agility_3cone'] + df['Shuttle']
df['Power_Ratio'] = df['Bench_Press_Reps'] / df['Weight']

# E. Positional Percentiles & Z-Scores
for col in COMBINE_METRICS + ['Height', 'Weight', 'BMI', 'Speed_Score']:
    df[f'{col}_pos_pct'] = df.groupby(['Position'])[col].rank(pct=True)
    pos_mean = df.groupby('Position')[col].transform('mean')
    pos_std = df.groupby('Position')[col].transform('std').replace(0, 1).fillna(1)
    df[f'{col}_pos_z'] = (df[col] - pos_mean) / pos_std

# ─────────────────────────────────────────────────────────────────────────────
# 3. PREPARE BASE DATASET
# ─────────────────────────────────────────────────────────────────────────────
# Ensure categoricals are properly typed for native tree splits
for col in cat_features:
    df[col] = df[col].astype('category')

X_train = df.iloc[:len(train_df)].copy()
X_test = df.iloc[len(train_df):].copy()

# ─────────────────────────────────────────────────────────────────────────────
# 4. OUT-OF-FOLD BASE MODELS (5-Seed Averaging on 0.848 Params)
# ─────────────────────────────────────────────────────────────────────────────
N_SPLITS = 10
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=2024)

# 5 Seeds to guarantee maximum test-set stability
SEEDS = [42, 100, 777, 888, 2024]

oof_cb = np.zeros(len(X_train))
oof_lgb = np.zeros(len(X_train))
test_cb = np.zeros(len(X_test))
test_lgb = np.zeros(len(X_test))

print(f"── Training CatBoost & LightGBM ({len(SEEDS)} Seeds per Fold) ──")

for fold, (trn_idx, val_idx) in enumerate(skf.split(X_train, y)):
    print(f"\n--- Fold {fold + 1}/{N_SPLITS} ---")

    X_tr, y_tr = X_train.iloc[trn_idx], y[trn_idx]
    X_va, y_va = X_train.iloc[val_idx], y[val_idx]

    cb_val_preds = np.zeros(len(X_va))
    cb_test_preds = np.zeros(len(X_test))
    lgb_val_preds = np.zeros(len(X_va))
    lgb_test_preds = np.zeros(len(X_test))

    for seed in SEEDS:
        # 1. CatBoost (Exact 0.848 parameters)
        cb = CatBoostClassifier(iterations=2000, learning_rate=0.02, depth=6,
                                cat_features=cat_features, random_seed=seed+fold, verbose=0)
        cb.fit(X_tr, y_tr, eval_set=(X_va, y_va), early_stopping_rounds=150)

        cb_val_preds += cb.predict_proba(X_va)[:, 1] / len(SEEDS)
        cb_test_preds += cb.predict_proba(X_test)[:, 1] / len(SEEDS)

        # 2. LightGBM (Exact 0.848 parameters)
        lgb_model = lgb.LGBMClassifier(n_estimators=2000, learning_rate=0.015, max_depth=6, num_leaves=31,
                                       subsample=0.8, colsample_bytree=0.7, random_state=seed+fold, verbose=-1)
        lgb_model.fit(X_tr, y_tr, eval_set=[(X_va, y_va)], callbacks=[lgb.early_stopping(150, verbose=False)])

        lgb_val_preds += lgb_model.predict_proba(X_va)[:, 1] / len(SEEDS)
        lgb_test_preds += lgb_model.predict_proba(X_test)[:, 1] / len(SEEDS)

    oof_cb[val_idx] = cb_val_preds
    oof_lgb[val_idx] = lgb_val_preds

    test_cb += cb_test_preds / N_SPLITS
    test_lgb += lgb_test_preds / N_SPLITS

    # Print Fold AUCs (Averaged across 5 seeds)
    print(f"  CatBoost Fold AUC: {roc_auc_score(y_va, oof_cb[val_idx]):.5f}")
    print(f"  LightGBM Fold AUC: {roc_auc_score(y_va, oof_lgb[val_idx]):.5f}")

# ─────────────────────────────────────────────────────────────────────────────
# 5. RANK BLENDING (Math Fix for Probability Mismatch)
# ─────────────────────────────────────────────────────────────────────────────
print("\n── Base Model Overall OOF AUCs ──")
print(f"CatBoost : {roc_auc_score(y, oof_cb):.5f}")
print(f"LightGBM : {roc_auc_score(y, oof_lgb):.5f}")

# Convert raw probabilities to percentiles (0.0 to 1.0)
oof_cb_ranked = rankdata(oof_cb) / len(oof_cb)
oof_lgb_ranked = rankdata(oof_lgb) / len(oof_lgb)

test_cb_ranked = rankdata(test_cb) / len(test_cb)
test_lgb_ranked = rankdata(test_lgb) / len(test_lgb)

# Apply your exact proven 85/15 split on the synchronized ranks
final_oof = (oof_cb_ranked * 0.85) + (oof_lgb_ranked * 0.15)
final_test = (test_cb_ranked * 0.85) + (test_lgb_ranked * 0.15)

print(f"\n🏆 Final Stacked Ensemble OOF AUC: {roc_auc_score(y, final_oof):.5f} 🏆")

# ─────────────────────────────────────────────────────────────────────────────
# 6. SAVE SUBMISSION
# ─────────────────────────────────────────────────────────────────────────────
sub = pd.DataFrame({
    'Id': test_ids,
    'Drafted': final_test
})

sub.to_csv('submission_0848_rank_blended.csv', index=False)
print("\nPredictions securely saved to submission_0848_rank_blended.csv")
